import type { Metadata } from "next";
import PageHeader from "@/components/PageHeader";
import Icon from "@/components/Icon";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://sureodds.ng";
const f = '"Proxima Nova", Arial, sans-serif';
const fd = '"Druk Text Wide", "Arial Black", sans-serif';

export const metadata: Metadata = {
    title: "Creators Program | Sureodds",
    description: "Join the Sureodds Creators Program. Share your football expertise, build your audience, and earn from your content.",
    alternates: { canonical: `${SITE_URL}/creators` },
    openGraph: {
        type: "website",
        url: `${SITE_URL}/creators`,
        title: "Sureodds Creators Program",
        description: "Share your football expertise, build your audience, and earn from your content on Sureodds.",
        images: [{ url: `${SITE_URL}/logo.png`, width: 800, height: 800, alt: "Sureodds" }],
    },
};

const perks = [
    { icon: "audience" as const, title: "Build your audience", body: "Publish to Sureodds' existing readership of millions of football fans. Immediate distribution without starting from zero." },
    { icon: "money" as const, title: "Earn from your content", body: "Creators earn a share of ad revenue generated by their content. The more your articles are read, the more you earn." },
    { icon: "badge" as const, title: "Expert badge", body: "Verified creators get a prominent expert badge on their profile and articles, building trust with readers." },
    { icon: "chart" as const, title: "Analytics dashboard", body: "Track your article performance, reader engagement, and earnings in real time through your creator dashboard." },
    { icon: "support" as const, title: "Editorial support", body: "Our editorial team is available to help with ideas, feedback, and SEO optimisation to help your content perform." },
    { icon: "target" as const, title: "Sponsored opportunities", body: "Top creators get first access to paid sponsorship and branded content opportunities from our advertising partners." },
];

const steps = [
    { num: "01", title: "Apply", body: "Send us your football expertise, a short bio, and two or three writing samples." },
    { num: "02", title: "Review", body: "Our editorial team reviews your application within 3–5 business days." },
    { num: "03", title: "Onboard", body: "Approved creators get access to our CMS, style guide, and creator dashboard." },
    { num: "04", title: "Publish", body: "Start publishing. Your content goes live to our full audience immediately." },
];

export default function CreatorsPage() {
    return (
        <div style={{ backgroundColor: "#fff", minHeight: "100vh" }}>
            <style>{`
                .cr-perks { display: grid; grid-template-columns: repeat(3,1fr); gap: 2.4rem; margin-bottom: 7rem; }
                .cr-steps { display: grid; grid-template-columns: repeat(4,1fr); gap: 2rem; margin-bottom: 7rem; }
                .cr-card  { padding: 2.8rem; border: 1.5px solid #e8ebed; border-radius: 1.2rem; }
                .cr-icon  { width: 4.8rem; height: 4.8rem; border-radius: 1rem; background: #f2f5f6; display: flex; align-items: center; justify-content: center; margin-bottom: 1.6rem; }
                @media(max-width:900px){
                    .cr-perks { grid-template-columns: repeat(2,1fr); }
                    .cr-steps { grid-template-columns: repeat(2,1fr); }
                }
                @media(max-width:600px){
                    .cr-perks { grid-template-columns: 1fr; }
                    .cr-steps { grid-template-columns: 1fr 1fr; gap: 1.6rem; }
                }
            `}</style>

            <PageHeader
                title="Creators Program"
                subtitle="Share your football expertise with millions of fans and earn from your content."
                image="https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1600&q=80"
                badge="Join the program"
                badgeColor="#ff6b00"
            />

            <div style={{ maxWidth: "132.48rem", margin: "0 auto", padding: "6rem 1.6rem 8rem" }}>

                <h2 style={{ fontFamily: fd, fontWeight: 700, fontSize: "clamp(2.4rem,4vw,3.2rem)", color: "#1a1a1a", textTransform: "uppercase", marginBottom: "3.2rem" }}>
                    Why join?
                </h2>
                <div className="cr-perks">
                    {perks.map(p => (
                        <div key={p.title} className="cr-card">
                            <div className="cr-icon">
                                <Icon name={p.icon} size={24} color="#ff6b00" />
                            </div>
                            <h3 style={{ fontFamily: fd, fontWeight: 700, fontSize: "1.6rem", color: "#1a1a1a", textTransform: "uppercase", marginBottom: "0.8rem" }}>{p.title}</h3>
                            <p style={{ fontFamily: f, fontSize: "1.5rem", color: "#68676d", lineHeight: 1.65 }}>{p.body}</p>
                        </div>
                    ))}
                </div>

                <h2 style={{ fontFamily: fd, fontWeight: 700, fontSize: "clamp(2.4rem,4vw,3.2rem)", color: "#1a1a1a", textTransform: "uppercase", marginBottom: "3.2rem" }}>
                    How it works
                </h2>
                <div className="cr-steps">
                    {steps.map(s => (
                        <div key={s.num} style={{ padding: "2.4rem", backgroundColor: "#f2f5f6", borderRadius: "1.2rem" }}>
                            <p style={{ fontFamily: fd, fontWeight: 700, fontSize: "4rem", color: "#ff6b00", lineHeight: 1, marginBottom: "1.2rem" }}>{s.num}</p>
                            <h3 style={{ fontFamily: fd, fontWeight: 700, fontSize: "1.6rem", color: "#1a1a1a", textTransform: "uppercase", marginBottom: "0.6rem" }}>{s.title}</h3>
                            <p style={{ fontFamily: f, fontSize: "1.4rem", color: "#68676d", lineHeight: 1.6 }}>{s.body}</p>
                        </div>
                    ))}
                </div>

                <div style={{ backgroundColor: "#1a1a1a", borderRadius: "1.6rem", padding: "5rem 3.2rem", textAlign: "center" }}>
                    <h3 style={{ fontFamily: fd, fontWeight: 700, fontSize: "clamp(2.4rem,4vw,3.6rem)", color: "#fff", textTransform: "uppercase", letterSpacing: "0.03em", marginBottom: "1.6rem" }}>
                        Ready to apply?
                    </h3>
                    <p style={{ fontFamily: f, fontSize: "1.7rem", color: "#888", maxWidth: "52rem", margin: "0 auto 3.2rem", lineHeight: 1.65 }}>
                        Send us your details, a short bio, and two or three writing samples.
                    </p>
                    <a href="mailto:creators@sureodds.ng?subject=Creators Program Application"
                        style={{ display: "inline-block", padding: "1.4rem 3.6rem", backgroundColor: "#ff6b00", borderRadius: "0.8rem", fontFamily: fd, fontSize: "1.5rem", fontWeight: 700, color: "#fff", textDecoration: "none", textTransform: "uppercase", letterSpacing: "0.04em" }}>
                        Apply Now →
                    </a>
                    <p style={{ fontFamily: f, fontSize: "1.3rem", color: "#555", marginTop: "1.6rem" }}>
                        creators@sureodds.ng
                    </p>
                </div>

            </div>
        </div>
    );
}
