[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y chromium-browser && echo 'Chromium:' && which chromium-browser && npm install"

[deploy]
startCommand = "node --require ts-node/register index.ts"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
